### PR TITLE
[LOC] Back-Translation "ヘルプ"→"Help"

### PR DESCRIPTION
**Pull request by hyoshioka0128**
https://docs.microsoft.com/ja-jp/nuget/tools/cli-ref-spec

### CODE REVIEW

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Comment by srvbpigh** [comment]
@hyoshioka0128 様、

ご提案いただきありがとうございます。 ご提案に同意のため、この PR をマージします。ご提案は、次回のアーティクルの更新でも使用されます。

 
敬具

Microsoft DOCS グローバル エクスペリエンス チーム

**Comment by olprod** [comment]
The PR is not being built because the target branch `live` is filtered in `.openpublishing.publish.config.json` on `live` branch.

**Comment by v-maudel** [comment]
Hello, @hyoshioka0128  

Thank you for your feedback and suggestions.
 
This proposed file change has been accepted. The suggestion will be merged to this repository.  We will release this article on the next localization release round. 
 
Many thanks for your support.

Kind regards,

Microsoft C&E Localization Team

**Pull request merged**
